exclude_inputs:
  name: Exclude inputs
  description: Exclude alarm inputs by writing 0 to the Modbus coil.
  target:
    entity:
      domain: alarm_control_panel
      integration: elmo_modbus
  fields:
    input_entities:
      name: Input sensors
      description: Alarm input binary sensors to exclude.
      selector:
        entity:
          domain: binary_sensor
          integration: elmo_modbus
          multiple: true
    inputs:
      name: Input numbers
      description: Alarm input numbers (1-1024) to exclude.
      example:
        - 1
        - 2
      selector:
        object:
include_inputs:
  name: Include inputs
  description: Reactivate alarm inputs by writing 1 to the Modbus coil.
  target:
    entity:
      domain: alarm_control_panel
      integration: elmo_modbus
  fields:
    input_entities:
      name: Input sensors
      description: Alarm input binary sensors to reactivate.
      selector:
        entity:
          domain: binary_sensor
          integration: elmo_modbus
          multiple: true
    inputs:
      name: Input numbers
      description: Alarm input numbers (1-1024) to reactivate.
      example:
        - 1
        - 2
      selector:
        object: